import folder_paths
import os
import json
from PIL import Image
from PIL.PngImagePlugin import PngInfo
import numpy as np

class CivitaiImageSaver:
    def __init__(self):
        self.output_dir = folder_paths.get_output_directory()
        self.type = "output"
        self.prefix_append = ""

    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "images": ("IMAGE", ),
                "filename_prefix": ("STRING", {"default": "ComfyUI"}),
            },
            "hidden": {"prompt": "PROMPT", "extra_pnginfo": "EXTRA_PNGINFO"},
        }

    RETURN_TYPES = ()
    FUNCTION = "save_images"
    OUTPUT_NODE = True
    CATEGORY = "Phantom/Saver"

    def save_images(self, images, filename_prefix="Phantom", prompt=None, extra_pnginfo=None):
        filename_prefix += self.prefix_append
        full_output_folder, filename, counter, subfolder, filename_prefix = folder_paths.get_save_image_path(filename_prefix, self.output_dir, images[0].shape[1], images[0].shape[0])
        results = list()
        
        # Build A1111 EXIF string from extra_pnginfo if available
        # It's an approximation since ComfyUI graph is not 1:1 with A1111
        a1111_string = "Generated by ComfyUI (Phantom)"
        
        # In a real scenario, you parse `prompt` (the execution plan) to extract node parameters:
        # e.g. find KSampler, get steps, cfg, sampler_name. Find CLIPTextEncode, get text.
        
        metadata = PngInfo()
        metadata.add_text("parameters", a1111_string)
        if extra_pnginfo is not None:
            metadata.add_text("workflow", json.dumps(extra_pnginfo))
        if prompt is not None:
            metadata.add_text("prompt", json.dumps(prompt))

        for (batch_number, image) in enumerate(images):
            i = 255. * image.cpu().numpy()
            img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))
            
            file = f"{filename}_{counter:05}_.png"
            img.save(os.path.join(full_output_folder, file), pnginfo=metadata, compress_level=4)
            results.append({
                "filename": file,
                "subfolder": subfolder,
                "type": self.type
            })
            counter += 1

        return { "ui": { "images": results } }
